- hosts: Master
  become: true
  vars_files:
    - aws_credentials
    - aws_vars
  tasks:
    - name: install aws CLI
      packages:
        name: awscli
        state: present

    - name: configure aws CLI
      shell: |
        aws configure set aws_access_key {{access_key}}
        aws configure set aws_secret_key {{secret_key}}
        aws configure set default.region {{aws_region}}
      args:
        executable: bin/bash

    - name: configure kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: "0755"

    - name: update kube config
      shell: "aws eks --region= {{aws_region}} update-kubeconfig --name {{eks-cluster-name}}"
      args: 
        executable: bin/bash
